### PR TITLE
Add Luxury Red and Bound to be Blue

### PR DESCRIPTION
**Pull request by DeveloperWOW64**
Nice, minimalistic themes.
Luxury Red:
Dark:
Dark Mode
Light: (Personally works better when default blue windows colour applied)
light mode
Bound to be Blue:
Dark:
Dark Mode
Light:
Light mode

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@DeveloperWOW64 What about the theme makes it "macOS"?

**Comment by DeveloperWOW64** [comment]
I made it based on some of the colours used in the macos

**Comment by yaichenbaum** [comment]
@DeveloperWOW64 I think we should stay away from using "macOS" in the name to avoid confusion about the themes.

**Comment by DeveloperWOW64** [comment]
ok. renamed to Luxury Red

**Comment by DeveloperWOW64** [comment]
how would I do that?

**Comment by yaichenbaum** [comment]
Here is an example https://github.com/files-community/Custom-themes/blob/main/CustomThemesPackage/Middle%20Blue.xaml#L13.

**Comment by DeveloperWOW64** [comment]
ok. I'll have a go

**Comment by DeveloperWOW64** [comment]
should be good

**Review by yaichenbaum — APPROVED** [review]
LGTM

**Pull request merged**
