### PR TITLE
Add Modern House

### PR DESCRIPTION
**Pull request by DeveloperWOW64**
Modern black/white theme for Microsoft Windows
Dark: 
image
Light:
image

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@DeveloperWOW64 Would it be possible to target this skin for Files v2? Let me know if you need access to the preview version.

**Comment by DeveloperWOW64** [comment]
What do you mean by that?

**Comment by yaichenbaum** [comment]
@DeveloperWOW64 The custom skin you designed is for v1.5, we've made multiple changes since then so it would be best to target the custom skin with those changes in mind.

**Comment by DeveloperWOW64** [comment]
Oh.

**Comment by DeveloperWOW64** [comment]
Wait, there seems to be an update available for files...

**Comment by DeveloperWOW64** [comment]
updated just now. The theme doesn't work the way intended anymore.

**Comment by yaichenbaum** [comment]
@DeveloperWOW64 yeah, we changed the way custom skins work so you might want to look at the documentation again to make sure you are up to date.

**Comment by DeveloperWOW64** [comment]
> @DeveloperWOW64 Would it be possible to target this skin for Files v2? Let me know if you need access to the preview version.

Ok, I'll see if I can remake it. I signed up for the insiders but haven't recieved an email back. Mind if you give me access to the preview version?

**Comment by yaichenbaum** [comment]
@DeveloperWOW64 I just added you to the flight group.

**Comment by DeveloperWOW64** [comment]
How exactly to I download Files Insider?

**Comment by yaichenbaum** [comment]
The Store version of Files should update to the latest preview.

**Comment by DeveloperWOW64** [comment]
hmm. it's not doing anything special.

**Comment by DeveloperWOW64** [comment]
It's still not doing anything. I refreshed the updates and downloads of the ms store to see if that helps, but it said everything is up to date.

**Comment by yaichenbaum** [comment]
@DeveloperWOW64 Can you base your theme off the sample theme in the documentation?

**Comment by DeveloperWOW64** [comment]
ok. i'll see what i can do

**Pull request closed without merging**
