### PR TITLE
Added Acrylic theme

### PR DESCRIPTION
**Pull request by winston-de**
https://github.com/files-community/Files/issues/4944

Dark theme:
image

Light theme:
image

A few surfaces (eg. navigation toolbar) are currently not possible to be overridden with an acrylic brush because they use a color as the background instead of a brush.

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@winston-de I believe we have brushes we can use for those surfaces, would you like to open a PR on the Files repo?

**Review by yaichenbaum — APPROVED** [review]
LGTM

**Comment by JotaRata** [comment]
Thank for this theme I'm loving it

**Comment by winston-de** [comment]
Glad you like it! :D

**Comment by Peter20130402** [comment]
how to download

**Pull request merged**
