### PR TITLE
Moved themes to optional package

### PR DESCRIPTION
**Pull request by winston-de**
This moves the themes to an optional package that can be installed alongside Files. 
Note, if you would like to test this with https://github.com/files-community/Files/pull/4574, you will have to change ```<uap3:MainPackageDependency Name="Files" />``` to ```<uap3:MainPackageDependency Name="FilesDev" />```

### CODE REVIEW

**Review by yaichenbaum — APPROVED** [review]

**Comment by yaichenbaum** [comment]
@winston-de Thanks!

**Comment by yaichenbaum** [comment]
@winston-de Should the themes be moved to their own sub folder?

**Comment by winston-de** [comment]
@yaichenbaum Maybe, I thought it would be more convenient in the root since we aren't putting anything else in it.

**Comment by yaichenbaum** [comment]
I am not sure, having it in a separate folder might be easier to navigate.

**Pull request merged**
